twitter/api.py

Made changes in api.py file, added the profile image update support. Just call `api.UpdateImage(file)`

update profile image support

---

twitter.py

allows for passing lists of users to lookup

added rate limiting to get-user-timeline

---

twitter/api.py

Let's make a new method GetFollowerIDsPaged to make it possible for a user to iterate over the list of followers using a cursor, in the same way as in GetFollowersPaged.
It will make it possible for the user to get the list of all followers of the given user by chaining GetFollowerIDsPaged calls with UsersLookup calls which in sum require less sleeping time than a GetFollowers loop.

Introduce GetFollowerIDsPaged which is similar to GetFollowersPaged.

---

AUTHORS.rst
twitter/parse_tweet.py
twitter_test.py

2) Add tests for emoticons in parse_tweet feed
3) Update Authors to reflect this contribution and original parse_tweet API

1) Add Emoticons parsing to the Tweet API.

---

twitter/api.py

The twitter api has support for since, so I'm adding that as well.

Adding since to getSearch

---

twitter/api.py

implemented method for Twitter API endpoint lists/memberships

added GetMemberships method

---

twitter/api.py

I added UpdateBackgroundImage method to connect to the corresponding endpoint.
UpdateProfile now takes profile_link_color to more accurately reflect the twitter endpoints capabilities.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bear/python-twitter/260)

Added UpdateBackgroundImage method and added profile_link_color argument to UpdateProfile

---

twitter/api.py

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bear/python-twitter/272)

Python3 compatibility fixes for print statement in authorization check & doc strings

---

twitter/api.py

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bear/python-twitter/275)

Honor 'count' parameter in API calls

---

README.rst

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/bear/python-twitter/289)

make print examples in README python3-compatible

---

twitter/api.py

Mostly copied how UsersLookup works. Didn't wrap the _ParseAndCheckTwitter call in a try block, as I wasn't sure what errors to be checking for there.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/bear/python-twitter/290)

Made LookupFriendship accept multiple users

---

twitter/api.py

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/python-twitter/318)

Implement Incoming, Outgoing and Show Friendship for Issue #317

---

doc/getting_started.rst

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/python-twitter/349)

add missing comma to example code

---

twitter/twitter_utils.py

It resolves #352
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/python-twitter/353)

Passing None media_type

---

tests/test_media.py
twitter/models.py

Fixes issue #357
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/python-twitter/360)

Add sizes attribute to twitter.Media objects

---

.gitignore
Makefile
circle.yml
requirements.docs.txt
requirements.testing.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/python-twitter/367)

update requirement files to remove versions

---

README.rst

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/python-twitter/382)

Fixed typo in readme

---

examples/view_friends.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/python-twitter/399)

Fix view_friends sample

---

twitter/api.py

Closes issue #397
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/python-twitter/400)

Update inline documentation re raw_query on GetSearch

---

doc/getting_started.rst

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/python-twitter/410)

added missing comma in example

---

twitter/api.py

These say "add" instead of "remove".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/python-twitter/442)

Fix documentation of DestroyListsMember method.

---

examples/tweet.py

In Python 3, ConfigParser has been renamed to configparser for PEP 8 compliance.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/python-twitter/444)

import configparser

---

twitter/api.py

Generally modernizes `UsersLookup()` and `GetUser()` to current style and practices for error checking and updates docstrings.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/python-twitter/448)

Fix issue with set indexing in UsersLookup

---

doc/getting_started.rst

Just a minor change that might avoid confusion for novice users. Thanks!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/python-twitter/467)

syntax clarification, twitter.Api() object creation

---

twitter/api.py

Since the API does not require authentication statuses/oembed, no need to enforce authentication.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/python-twitter/477)

Added enforce_auth argument

---

twitter/api.py

As-is, python-twitter wasn't great for actually opening a long-lived connection in a long-lived worker. This changeset refactors the `GetUserStream` method and its supporting infrastructure so that users can opt into manually controlling the requests session used for control over connection pooling / lifetime, as well as exposing Twitter's empty keepalive signals to the user should they choose to opt in.
These changes are currently live as a vendored copy of python-twitter in my skrode project.
These were quick and dirty changes to get the behavior I needed, I'd be pleased to clean it up some for you if there are comments. Just figured I'd offer these changes rather than let them languish in my vendored copy.
---
This change is [<img src="https://reviewable.io/review_button.svg" …

Support request Sessions for streaming, warn about the timeout floor

---

twitter/models.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/python-twitter/534)

Update User model to include missing attributes

---

twitter/api.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/python-twitter/553)

Fix typo in docstring of Api

---

Makefile
circle.yml

Updates the supported python versions to 2.7.15, 3.6.5, and includes pypy3.5 since those tests now pass.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/python-twitter/563)

Update Python Versions

---

twitter/api.py

This line print the parameters when you call UsersLookup. It shouldn't be there
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/python-twitter/570)

Deleted uncomfortable print

---

twitter/api.py

A pull request in reference to issue https://github.com/bear/python-twitter/issues/600
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/python-twitter/601)

Added _ParseAndCheckTwitter to PostDirectMessage API call

---

README.rst

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/python-twitter/605)

fix simple typos

---

requirements.testing.txt
requirements.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/python-twitter/610)

fix requests-oauthlib dependency

---

twitter/api.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/python-twitter/620)

Some small updates

---

doc/getting_started.rst

Closes #637
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/python-twitter/638)

Clarify API creation example

---

twitter/api.py

Hey everyone, love the library! I'm using it in combination with some other APIs and libraries that supply images, one thing I ran into was `UpdateBanner()` only allowed local files - I wanted to avoid having to save images to my disk so I added the ability to supply external urls and base64 strings of images. Thought it'd be useful for someone else so here is my PR!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/python-twitter/626)

add external urls, base64 string options to UpdateBanner

---

doc/getting_started.rst

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/python-twitter/657)

Typo in docs: getting_started.rst

---

twitter/api.py

update comments on lines 3552 & 3554, from 'mark' to 'unmark'
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/python-twitter/689)

correct descriptions of methods in api.py

---

setup.py

Accidentally re-added in #573.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/python-twitter/706)

Remove `future` dependency (again)

---

twitter/api.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/python-twitter/698)

Fix docs to fit expected keyword argument

---

twitter/api.py

it was listed twice
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/python-twitter/676)

Remove redundant PostDirectMessage

---

twitter/api.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/python-twitter/655)

Update documentation for GetListMembers
