twitter/_file_cache.py

When running e.g. gunicorn, sometimes the worker processes concurrently check for the tmp dir and then both attempt to create it:
```
[2015-02-16 15:01:46 +0000] [14] [ERROR] Exception in worker process:
Traceback (most recent call last):
File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 503, in spawn_worker
worker.init_process()
File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 116, in init_process
self.wsgi = self.app.wsgi()
File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
self.callable = self.load()
File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
return self.load_wsgiapp()
File …
```

Fix race condition in _InitializeRootDirectory

---

twitter/_file_cache.py

Pull request #214 introduced a reference to "errno", but the module was not imported. In some cases it works, but in others it will fail.
Run
```
python twitter_test.py FileCacheTest
```
to verify. Also cleaned up imports according to PEP8.

Fix missing "errno" import introduced in pull request #214.

---

twitter/_file_cache.py
twitter/api.py
twitter/direct_message.py
twitter/status.py
twitter_test.py

Here's some fixes to get the tests passing on py3 with the exception of the api tests, which seem to have been already broken because they try to call SetUrllib to use a mock urllib which has apparently been removed.
Might have a crack at fixing that up too at some point.
Tested on python 2.7, 3.4.

fix tests that weren't already broken on py3

---

twitter/api.py

Sets the default page size for `GetFriendIDs` to 5000 and updates an out of date doc string.

Set default page size for GetFriendIDs to 5000

---

twitter/api.py

After receiving many of the following errors:
{"errors":[{"code":324,"message":"The validation of media ids failed."}]}
And reading here: https://twittercommunity.com/t/the-validation-of-media-ids-failed-error-code-324/29304
I found that Twitter would give this error if you tried to upload more than 4 images at a time. As an immediate fix I'm truncating the list to the maximum that twitter will accept.

Fix for PostMultipleMedia media-ids-failed-error

---

twitter/api.py

There was a typo where it was copied and pasted from another method.

Correct GetListsList docstring

---

doc/twitter.html
twitter/api.py

Fix for Issue https://github.com/bear/python-twitter/issues/240
- Remove references in both docstrings (located in api.py) and the html docs themselves, to a deprecated function (`GetUserByEmail(email)`)

Remove references to outdated API functionality: GetUserByEmail

---

twitter/api.py

Python-Twitter API currently fails because json doesn't have bytestream support for encoding. This fix converts all json.content from bytestream into unicode-strings before passing them to json.

Python-3 Fix: decode bytestreams for json load

---

tests/test_status.py
twitter/status.py

Hello,
I don't know if this was exactly what you guys were thinking here https://github.com/bear/python-twitter/issues/222, but I implemented one __repr__ for status. If this was not the standard, I can change with your instructions.
Thanks :)

Add __repr__ for status

---

twitter/trend.py

Hi,
When ```__repr__``` is called on a Trend object, non-ASCII character leads to a UnicodeEncodeError.
*When did this bug occur?*
I am a German twitter User. The API broke on a Trend with name 'Dinge die Mädchen'. The ä is a non-ASCII character.  The full error code was:
```UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 11: ordinal not in range(128)```
I am not sure, if this may occur in other method calls. Basically, Non-ASCII characters should be supported, since twitter is used world-wide.
Thanks for the great API.
Cheers
Daniel

Fixed Non-ASCII printable representation in Trend

---

setup.py
twitter/__init__.py
twitter/api.py
twitter/category.py
twitter/media.py
twitter/status.py

Hey!
So I needed these endpoints for a project I'm working on at work so I thought I would add them :)
Follows your normal layout and I added some classes too.
Works like a charm :)
Happy to clean up/Add any more doco so we can merge it back in just let me know.
It's been kind of a rushed job since I needed it to work asap haha.
Thanks for your lib it rocks!!

Adding api methods for suggestions and suggestions/:slug

---

twitter/api.py

All changes for this pull request are within the api.py file.
-- Added _GetIDsPaged which has the almost all of the logic that used to be in GetFollowerIDsPaged.  This function is used for both the friends and the followers case.
-- GetFollowerIDsPaged and the new GetFriendIDsPaged now call _GetIDsPaged.
-- GetFriendIDs now calls GetFriendIDsPaged in the same manner that GetFollowerIDs uses to call GetFollowerIDsPaged.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bear/python-twitter/259)

Added GetFriendIDsPaged

---

tests/test_media.py
twitter/media.py

I noticed that, since Python 3 removed the `iteritems()` (see line 32) method for dictionaries, constructing a Media object fails.
I also updated the Media object to have parity with User and Status objects with:
* `AsJsonString()` 
* `__str__`
* `__ne__`
methods, since those are present on other objects; Media objects should probably get an ID as well, since this is included with the response from twitter (and might be helpful with chunked media depending on how that gets implemented). 
This is my second pull request, so let me know if I'm doing something wrong. New tests are included, since it doesn't look like Media gets tested as it currently stands.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on …

Updates Media object with new methods, adds id param, adds tests

---

twitter/api.py

full_text option:
If we don't do that there is a link to the twitter website to see the discussion
page option:
If we have more than 200 unread messages, you can't reach them with the count option. Page option is the answer for this matter.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bear/python-twitter/266)

Add full_text and page options in GetDirectMessages function

---

twitter/api.py

This eliminates `AttributeError: 'Api' object has no attribute '_Api__auth'` errors by initializing `Api.__auth` to None. Now, setting the authentication parameters incorrectly results in the proper error message: `TwitterError: {'message': 'Api instance must first be given user credentials.'}`.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bear/python-twitter/267)

initialize Api.__auth fixes #119

---

twitter/api.py

PyLint throws an error for redefinition of `json` in twitter/api.py; this change also standardizes the way the response from the `self._RequestUrl()` is named (it's currently either `json`, `json_data`, or `r`). 
Also fixes errors on lines 497 & 516 where the json string wasn't being properly decoded (no `.decode('utf-8')` on the response from Twitter), which would raise a TypeError in `_ParseAndCheckTwitter` with the statement `data = json.loads(json_data)`
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bear/python-twitter/270)

Fixes lint & TypeError

---

README.rst

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bear/python-twitter/279)

Fixed wrong link target of PyPI badge

---

twitter/api.py
twitter/twitter_utils.py

* Adds ability to chunk media uploads for videos and large GIFs.
* Method can be called by itself; there's no requirement to use PostUpdate(). Return value will be the `media_id` of the media that was uploaded.
* For smaller uploads, such as photos that don't require chunked uploads.
* Method can be called by itself; there's no requirement to use PostUpdate(). Return value will be the `media_id` of the media that was uploaded.
* Now has an attribute called `chunk_size`. The default is 1MB, which seems sensible at the moment. (My RPI2 is working with 3MB chunks for a video bot and it seems fine, but that's literally the only thing that computer does.) 
* If you try to set `chunk_size` below 16KB, then the API will warn you since a 15MB video divided into 15KB chunks will result in > 1000 …

Adds ChunkedMedia Uploads (videos/gifs) and Deprecates PostMultipleMedia & PostMedia

---

setup.py

That fact aside, there is a Python3 and unicode issue with the setup.py file, specifically, in how it opens and reads AUTHORS.rst:
+ /usr/bin/python3 setup.py build '--executable=/usr/bin/python3 -s'
Traceback (most recent call last):
File "setup.py", line 40, in <module>
read('AUTHORS.rst') + '\n\n' +
File "setup.py", line 27, in read
return f.read()
File "/usr/lib64/python3.4/encodings/ascii.py", line 26, in decode
return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 412: ordinal not in range(128)
This only fails on Python 3 (I tested with 3.4.3). Since we know the encoding of the files is UTF-8, and we aren't concerned about these open() calls for performance, being explicit with encoding='utf-8' and using io.open is the …

Unicode + Python = day drinking. 

---

tests/test_api_30.py
twitter/api.py

Geocode information can now be passed directly as a string: `"37.781157,-122.398720,1mi"` or a list/tuple such as `[37.781157,-122.398720,"1mi"]`.
Inline documentation has been updated to reflect change. All tests passing & should not break old behavior.
Added type checking for the other search parameters and updated inline docs for what parameter types `GetSearch()` method expects.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/bear/python-twitter/296)

Fix for issue #232 in GetSearch() geocode

---

doc/migration_v30.rst
testdata/get_friendships_lookup_muting.json
testdata/get_friendships_lookup_muting_blocking.json
testdata/get_friendships_lookup_none.json
tests/test_api_30.py
twitter/api.py
twitter/user.py

Per discussion on #290 , LookupFriendship can take either ints/strings/Users or lists of those for ``user_id`` or ``screen_name``. Add tests and data for method. 
In working on this, I noticed that Twitter returns some additional information on querying that endpoint. In addition to ``following`` and ``followed_by`` there is now:
* ``following_received`` (your account is private, target user has requested to follow you),
* ``following_requested`` (target user is private, you've requested to follow them), 
* ``muting`` and ``blocking`` (target user is muted or blocked by authenticated user).
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/bear/python-twitter/297)

Update to LookupFriendship

---

twitter/api.py

The streaming endpoints didn't properly decode the bytes-string from the response when passing to ``_ParseAndCheckTwitter()``, thereby raising a ``TypeError`` when calling ``json.loads()`` on the response from Twitter.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/bear/python-twitter/300)

fixes content.decode errors for streaming endpoints

---

twitter/api.py

When passing coordinates to `api.GetStreamFilter` the locations
parameter should specify coordinates as Longitude,Latitude pairs
instead of Latitude,Longitude
https://gist.github.com/meyersj/234a59604fde81c0d036
https://dev.twitter.com/streaming/reference/post/statuses/filter
https://dev.twitter.com/streaming/overview/request-parameters#locations
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/python-twitter/313)

Fix documentation for order of bbox coordinates

---

Makefile
doc/migration_v30.rst
twitter/api.py

This changes some of the keyword arguments so that they are a little more consistently named in the API and avoid renaming the builtin function ``id``. Kind of a small change, but I wanted to get it in before v3. Basically anything that was passed as ``id`` has a more descriptive argument now: ``id`` in the context of a Status object changes to ``status_id``, ``message_id`` for DirectMessages, and ``woeid`` for the Where On Earth ids. Similarly, for DestroyBlock, it's now ``user_id`` rather than just ``id``.
Documentation is included for everything here. All previous tests still pass, but some of the behavior is breaking since kwargs have been renamed.
I also noticed that ``make clean`` kept deleting my vim undo files, so I hope no one minds that those are excluded from the target.
Sound …

Consistency in keyword arguments for "id" parameters

---

tests/test_rate_limit.py
twitter/ratelimit.py

Regex was wrong such that `GetStatus` and `GetUser` would both try to get an endpoint that didn't exist. The previous error catching failed, because an `AttributeError` was never raised when trying to get a rate limit for an endpoint that didn't exist. So `GetStatus` was looking for rate limit information re `/statuses/show/123`, but the URL that method calls is just `/statuses/show.json` and the status_id is a query parameter. Same basic idea for `/users/show/456` v `/users/show.json`
This fixes that and amends the behavior to return a default rate limit object in the case that an endpoint is not found the first time around and then sets it the next time. This might cause some issues if Twitter consistently doesn't update their `/application/rate_limit_status.json` endpoint, but I think …

Fix for Issue 320 re Rate Limit

---

README.rst
doc/installation.rst

Fix for issue #323. I pulled from master and typed `grep -r
readthedocs.org *`. It returned 7 results and I changed all 7 of those to
readthedocs.io.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/python-twitter/324)

Update all readthedocs.org to readthedocs.io

---

README.rst

Badge URLs were broken. Looks like the badges for RTDs are staying on the .org domain? They may also just not be redirecting yet, since the change just went live.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/python-twitter/325)

Fix Badge URLs for CircleCI and ReadtheDocs

---

tests/test_status.py
twitter/models.py

Removes `Status.Now` property, `Status._now` & `Status.now` attributes, and tests per discussion on #331.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/python-twitter/332)

Removes relative dates for Status object per issue #331

---

doc/migration_v30.rst
twitter/api.py

From discussion on #298, we're removing the `shortner` param from the API. This change removes it and documents the change on the migration guide.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/python-twitter/333)

Removes shortner param from API per #298

---

twitter/models.py

Twitter API has field "following" in User's model. It shows if your account is following that user.
https://dev.twitter.com/rest/reference/get/users/show
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/python-twitter/351)

Missing field "following" added to User model

---

tests/test_api_30.py
twitter/api.py

Fixes issue #355: `category.Slug` attribute should be `category.slug` in `Api.GetUserSuggestion()`. Adds tests for `GetUserSuggestion()` & `GetUserSuggestionCategories()`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/python-twitter/356)

Fix for Issue 355

---

twitter/api.py

first pass is to make the 401 handled cleaner and then look into why we are getting a 401 at all for Steams
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/python-twitter/364)

start on fix for Issue #363

---

tests/test_rate_limit.py
twitter/api.py
twitter/ratelimit.py

Adds ability to set rate limit endpoints even if `api.sleep_on_rate_limit` is False
Basically, if you instantiate an Api instance with `sleep_on_rate_limit=False`, then previously we would not keep track of the data returned in the headers that pertained to the rate limit. My thinking is that there could be a use case where you don't want the Api to sleep for 15 minutes (the default behavior when you're rate limited), but would rather have the program do something else. 
This change has the Api keep track of the rate limit status of any endpoint that the user specifically calls, but won't, on its own, go out and obtain the full rate limit endpoint and doesn't force the user into the default sleeping behavior.
---
This change is [<img src="https://reviewable.io/review_button.svg" …

fix issue 358

---

twitter/twitter_utils.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/python-twitter/372)

Added support for Quicktime (.mov) media uploads.

---

doc/changelog.rst
testdata/models/models_trend.json
tests/test_models.py
twitter/models.py

`Trend.volume` data should be populated on object creation, but because the json data from Twitter is named `tweet_volume`, this isn't occurring. This changes the property name to be `tweet_volume` which conforms with Twitter's naming convention and allows the property to be populated straight from the json data.
Additionally, an `@property` has been added to the `Trend` object for backwards compatibility. 
#374 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/python-twitter/375)

tweet_volume not being populated for Trend objects

---

tests/test_rate_limit.py
twitter/ratelimit.py

Setting `sleep_on_rate_limit` to `False` would cause the API to raise an exception by attempting to assign a value to `None` as though it were a dictionary. This was cause by the `rate_limit.set_limit` code not properly handling a case were an exception wasn't raised on
```python
try:
family_rates = self.resources.get(resource_family).get(endpoint)  # <-- this here.
except AttributeError:
self.set_unknown_limit(url, limit, remaining, reset)
family_rates = self.resources.get(resource_family).get(endpoint)
```
so `family_rates` would just be set to `None`, so when this
```python
family_rates['limit'] = enf_type('limit', int, limit)
```
happened, it'd raise a TypeError trying to set the `'limit'` attribute on a NoneType object.
Long story short, I deleted the offending `set_limit` code after …

Fix failure to set unknown rate limit while sleep_on_rate_limit == False

---

GAE.rst
README.rst
twitter/api.py

Added Google's monkeypatch so requests will use the appengine urlfetch library. Disabled caching for now because app engine does not work with the existing strategy.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/python-twitter/383)

Added Google's monkeypatch, disabled caching for now.

---

Makefile

Changes the `makefile` to get the `uname -m` (returning either "i686" for 32-bit systems or "x86_64" for 64-bit systems) and `uname -s` (returning "Linux" at least on Ubuntu and Arch) and, if it's "x86_64" & "Linux", then use the source distribution of pypy-5.3.
#378 
Running `make dev` on a 64-bit Linux system results in failure to install pypy-5.3, since only pypy-5.3-src is available for 64-linux.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/python-twitter/379)

Update makefile for use with pypy and 64 bit linux.

---

doc/changelog.rst
tests/test_models.py
twitter/models.py

Adds a full-hydrated User object to the DirectMessage object for the ``sender`` and ``recipient`` properties.
#344 
Tests added for DirectMessage Model. All prior tests pass.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/python-twitter/384)

Add User object to DMs per Issue #344

---

doc/changelog.rst
doc/twitter.rst
tests/test_api_30.py
twitter/api.py
twitter/error.py

Adds a couple things:
* PythonTwitterDeprecation warnings have been added to `twitter/error.py`. This is in the same vein as Django's warning release system where a deprecation warning is added prior to a release and has the release number included in the warning. So, for example, in version 3.2, there are a bunch of PythonTwitterDeprecation330 warnings letting you know what's going away in the next version.
* In that spirit, the previous deprecation warnings have been converted to PythonTwitterDeprecation330 warnings where appropriate.
* UpdateBackgroundImage now has a PythonTwitterDeprecation330 deprecation warning.
#341 
Unit tests added for deprecation of UpdateBackgroundImage. All new and old tests pass.
---
This change is [<img src="https://reviewable.io/review_button.svg" …

Add Descriptive Deprecations

---

tests/test_api_30.py
twitter/api.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/python-twitter/389)

Add support for non-ascii filenames in UploadMediaChunked

---

Makefile

This should fix the CI failures until PyPy3 gets out of alpha
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/python-twitter/412)

remove pypy3 for now and refactor Makefile a bit to remove redundancy

---

twitter/api.py

The twitter api expects the status id to be passed as 'id' rather than as 'status_id' in the request, as documented here https://dev.twitter.com/rest/reference/get/statuses/retweeters/ids
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/python-twitter/430)

Change URL parameter in GetRetweeters to match twitter api.

---

twitter/api.py

The value of os.environ.get('SERVER_SOFTWARE', '') only contains 'Google App Engine' when running on production. Local dev environments have a value like 'Development/X.Y'. Because of that, I was getting cache errors when running locally.
Instead of testing the value of the 'SERVER_SOFTWARE' key, testing for the presence of an 'APPENGINE_RUNTIME' key will work across both local and production environments.
(This is my first ever pull request for an open source project. Apologies if there's etiquette I've not followed.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/python-twitter/436)

Update GAE environ test

---

twitter/api.py

This fixes issue #426, where List functions defaulted to False for owner_screenname etc. than None, which caused those functions to fail and pass the wrong identifying info to Twitter.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/python-twitter/441)

Fix instances where kwargs should default to None

---

twitter/api.py

We were previously surfacing all warnings by setting `warnings.simplefilter` in the source of python-twitter itself. It seems like this is a decision best left to the end user whether and how (if they just want to see the warning or if they want to error out) they would like them handled. This removes that line of code.
Closes issue #403 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/python-twitter/440)

Fix warnings always being displayed at library level

---

tests/test_api_30.py
twitter/api.py
twitter/twitter_utils.py

Previously, if a GIF or a video was less than `self.chunk_size`, it would be uploaded via `UploadMediaSimple`, but this was a bug because that endpoint cannot handle videos or GIFs. This change makes it so that even if the video is small, it'll get passed to `UploadMediaChunked`.
Closes #433. All tests pass.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/python-twitter/439)

Fix to upload video/gifs to correct endpoint if filesize < self.chunk_size

---

twitter/api.py

According to the documentation (https://dev.twitter.com/rest/reference/get/statuses/retweeters/ids)
the cursoring parameter is called 'cursor' and not 'count'.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/python-twitter/451)

Change retweeters parameter to 'cursor'

---

twitter/api.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/python-twitter/449)

Proxy settings feature added

---

twitter/api.py

I tidied up  [bryanlandia@ b6a427a](https://github.com/bryanlandia/python-twitter/commit/b6a427ac151c839ee2553d3dd81e051b4da900c7) a little, notably to remove the requirement to provide an access token when using application-only authentication. Also changed (removed) exception trapping, to make the changes consistent with existing code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/python-twitter/423)

Reworked @bryanlandia extension to allow application-only authentication

---

twitter/api.py

- Added filter_level option to streams.
-- Specifies the level of filtering twitter applied to tweets.
-- https://dev.twitter.com/streaming/overview/request-parameters#filter_level
-- Optional, None is default, option of 'low' or 'medium'.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/python-twitter/462)

Added filter_level option to streams

---

twitter/api.py

If `media_id` was a `long` in python 2.7, then the `isinstance` checks `ints` would fail, causing problems for attaching a media object to a tweet.
Closes issue #438
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/python-twitter/463)

fix for case where media_id was long in PostUpdate isinstance check

---

tests/test_media.py
tests/test_status.py
tests/test_trend.py
tests/test_user.py
twitter/models.py

- Allows for creating Python set() objects containing Users, Statuses, etc.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/python-twitter/479)

Implement __hash__ on models with ID attributes

---

twitter/api.py

Because it seems we have to pass 'true'(not 'True') for the parameter to get `email` field in the response
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/python-twitter/493)

Fix `include_email` parameter of VerifyCredentials

---

twitter/api.py

I felt the need to dump sometimes the JSON stream instead of the object twitter.User
By default this feature is not active. 
Also, if this  pull request is accepted the tests might need an update, haven't touched those yet.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/python-twitter/501)

added param return_json (bool, optional):

---

twitter/api.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/python-twitter/505)

Removed 140 character limit from Api.PostDirectMessage method's doc

---

tests/test_api_30.py
twitter/api.py

- Fixes imports for py2/py3 with urllib.quote_plus
- Fixes issue with implicit string/bytes conversion with the headers
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/python-twitter/508)

Fix issue #494 for py3 compat w/ app only auth

---

tests/test_models.py
twitter/models.py

Because `UserStatus.connections` is a public variable, there is some confusion regarding its use (see #497). The original idea was that `UserStatus.connections` would only hold the default connection types available, much like the `param_defaults` attribute for other models; however, because of the name, it was implied that this attribute contained the connections for the specific instance, resulting in confusion between it and the intended attributes (i.e., `UserStatus.followed_by` etc).
This commit moves the attribute to a private attribute (`._connections`) so that it is clearer to end-users that it should not be used for a specific instance.
Additionally, this creates an `@property` with a dictionary containing the class-specific attributes for `UserStatus.following`, etc. to maintain …

move UserStatus.connections to private class attr

---

GAE.rst

I just tried to use the library in Gae and was missing the `requests_toolbelt`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/python-twitter/540)

Included requests_toolbelt in dependencies

---

tests/test_rate_limit.py
twitter/api.py

Add a local logger to api.py.
Use that logger to log a debug message when the user has been ratelimited.
Add a test which covers the time.sleep code path.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/python-twitter/544)

Logging ratelimit

---

twitter/api.py

2 seconds delta was not sufficient. It was throwing errors once the sleep is over. 
I have kept it at 10 seconds. 
This value either needs to be asked at the time of object creation or needs to be based on some stats rather than random selection. 
Will be more than happy to hear comments and suggestions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/python-twitter/542)

increasing delta time to sleep

---

twitter/api.py

fixes a minor issue in construction of dict passed to TwitterError
Signed-off-by: Thorsten Schwander <thorsten.schwander@gmail.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/python-twitter/560)

fix typo in dict passed to TwitterError

---

.gitignore
testdata/post_post_direct_message.json
tests/test_api_30.py
tests/test_models.py
twitter/api.py
twitter/models.py

This PR migrates the existing PostDirectMessage method to use the new Twitter API documented at https://developer.twitter.com/en/docs/direct-messages/sending-and-receiving/api-reference/new-event.
This is a breaking change as both the input format and the response format are quite different; for example `screen_name` is no longer supported as a parameter, and the return result also no longer contains hydrated `recipient` and `sender` objects.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/python-twitter/579)

migrate api.PostDirectMessage to new twitter api

---

twitter/api.py

'TwitterApi' requires a comma-separated string, but passed an array.
https://developer.twitter.com/en/docs/media/upload-media/api-reference/post-media-upload-init
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/python-twitter/599)

Fixed 'additional_owner' does not work properly

---

requirements.docs.txt
requirements.testing.txt
requirements.txt
setup.cfg
setup.py
tests/test_filecache.py

As suggested in #571, removed `future` dependency.
I've double checked and found no code that uses any of the backports provided by `future`.
All the code seems to be Python 2/3 compatible using `try ... except ImportError` and such.
Also took the chance to fix a few deprecation warnings I got while running the tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/python-twitter/614)

Remove `future` dependency

---

tests/test_api_30.py
tests/test_rate_limit.py

Since your commit d06a698773f5b8e520f8be954c83b2ec2ed13c8a there have been quite a few unit tests failing. These are all because of the new default value `tweet_mode=extended`.
I've updated the unit tests to account for this new default, and now they're all passing again.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/python-twitter/642)

Fix failing tests due to updated default tweet_mode

---

twitter/api.py

Hi everyone, Actually when you try to make a Search using GetSearch the system always returns 15 values (using default value of 15) even when you change this values to a different values between 0 and 100 (as specs) the system always display 15. I had to fix this for my project i am working in a private project for an important client and that was the solution.
The second part of the PR is a typo in the documentation in the same method.
Thanks for the your hard and awesome work creating this library :)
I hope it could help us. Have a great day.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/python-twitter/607)

Fix typing issue and parameter count issue in GetSearch method.

---

testdata/subs.srt
tests/test_api_30.py
tests/test_twitter_utils.py
twitter/api.py
twitter/twitter_utils.py

This PR fixes #643 
I've added support for uploading subtitle files (.srt). Twitter's API documentation around it isn't great, but I've cobbled it together from https://developer.twitter.com/en/docs/media/upload-media/uploading-media/media-best-practices and https://developer.twitter.com/en/docs/media/upload-media/api-reference/post-media-subtitles-create.
You can now upload an .srt file using UploadMediaChunked (with media_category set to "Subtitles"). When you also upload a video using the same function (but with media_category set to "TweetVideo"), you then need to call the new function PostMediaSubtitlesCreate to associate the video with the subtitles.
You can see how I used the library at https://github.com/danielthepope/tfl-tree/blob/master/tfltree/raspberrypi/tweets.py#L45
---
This …

Add ability to upload subtitles and link to media

---

twitter/api.py

According to twitter's api:
> Note: This parameter(in_reply_to_status_id) will be ignored unless the author of the Tweet this parameter references is mentioned within the status text. Therefore, you must include @username , where username is the author of the referenced Tweet, within the update.
user only specify in_reply_to_status_id arguement in api.PostUpadte may not work. api.Replyto automatically  add _@username_ before the message.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/python-twitter/487)

Add api.Replyto for convenience

---

twitter/api.py

At present, the twitter.Api does not contain verify and cert parameters which exist in requests.request. These parameters help in dealing with SSL certificate verification. In our project, we needed to bypass this verification but by default requests.request was verifying the SSL certificates and creating an issue for us. We simply included the said parameters in the twitter.Api as verify_ssl and verify_cert and used it subsequently in the call to requests.request
If some further changes are to be made, let us know - we could modify accordingly too
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/python-twitter/556)

twitter.Api - SSL Certificate Verification

---

MANIFEST.in

Hi,
We at Gentoo rely on PyPI tarballs to build docs and run tests. I understand that this means distributing a larger file.
It could also be beneficial to other distributions like Debian: https://lists.debian.org/debian-python/2016/04/msg00074.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/python-twitter/572)

Include doc, examples and tests in source distributions

---

twitter/api.py

Right now whenever the twitter API returns an un-parsable response that isn't explicitly known/handled, the TwitterException sets the message parameter to a `set` type, not a `dict` type or a `str` type (which is used in some cases elsewhere). 
This is causing errors for me as I'm inspecting this exception for graceful error handling, and received a `set` much to my surprise! Looks to me like a copy/paste bug. 
I'd like to have it be a `dict`, but if you think a `str` is more appropriate that works too! 
Thanks for the great library :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/python-twitter/606)

Fix typing issue in `Api._ParseAndCheckTwitter`

---

README.rst
setup.py

Dear Developers,
Thank you very much for your help.
I was looking at the [PyPI site of this project](https://pypi.org/project/python-twitter/3.5/).
And I found that the rich text was not compiling the right way, resulting in a broken layout.
So I tried to find out the cause of the problem. The reasons are the following two points.
1. "---" which indicates paragraph titles, is too short.
2. the "CHANGES" file contains indentations.
Adding some "-" solves problem 1.
The function which I added in setup.py solves problem 2.
I have confirmed on the [PyPI test server](https://test.pypi.org/project/python-twitter-test0/) that these fixes make the compilation work.
Another possible solution is to remove the "CHANGES" file from the PyPI long_descrition.
However, I decided that it would be better …

Fix for PyPI's README not being rendered correctly.

---

twitter/api.py

There is a small typo in twitter/api.py.
Should read `unsuccessful` rather than `unsuccesful`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/python-twitter/686)

docs: fix simple typo, unsuccesful -> unsuccessful

---

requirements.txt
setup.py
twitter/twitter_utils.py

mimetypes relies on file extension, while filetype relies on file header which is more stable.
#391
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/python-twitter/684)

replace mimetypes to filetype

---

twitter/api.py

The GetLists() method documents the count parameter,
which is actually not available in the method signature
and can't be used.
Due to this, the GetLists() method is basically limited to
retrieving ~300 lists at once, as the internally called
GetListsPaged() method will retrieve only 20 lists at once
and will hit rate limits after 15 calls in a row.
So add "count" to the method signature and pass it to
GetListsPaged(). Also add a note about rate limits & hint
to bump "count" once they start to be hit.
With this change a caller that passes say 500 as "count"
(tested) can retrieve 300+ lists without unnecessarily
hitting rate limits.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

Add documented but missing count to GetLists()

---

twitter/api.py

GetRetweets used to have `statusid` instead of `status_id`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/python-twitter/650)

fixed inconsistent naming of variable in api.GetRetweets

---

twitter/api.py

Fixes https://github.com/bear/python-twitter/issues/662.
This is my first commit to this repository and I do have a couple of questions.
1. Would it be preferred that we add the media category for all gifs?
2. Would it be better to pass the media category for all gifs?
Thank you for the help!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/python-twitter/663)

Feature: Allow ability to upload gifs in the range of 5MB to 15MB.

---

.gitignore
twitter/api.py

I discovered I wasn't getting the full_text attribute from the PostUpdate endpoint, only a truncated text. This is because Api._RequestUrl() only added the tweet_mode parameter to GET requests. But the Twitter API docs explicitly say: "add the [tweet_mode=extended] parameters to *any* endpoint" (my emphasis). https://developer.twitter.com/en/docs/tweets/tweet-updates
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/python-twitter/660)

Always add tweet_mode to API requests
